mixed-port: 7890
mode: rule
external-controller: 127.0.0.1:9090

# geoip设置
geodata-mode: false
geox-url:
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/latest/download/country-lite.mmdb"
etag-support: true
global-ua: clash.meta

dns:
  enable: true
  listen: 127.0.0.1:53
  ipv6: false
  dns-direct-nameserver:
    - 1.1.1.1
    - 1.0.0.1
  proxy-server-nameserver:
    - 1.1.1.1
    - 1.0.0.1
  nameserver:
    - https://1.1.1.1/dns-query#default
    - https://1.0.0.1/dns-query#default

  nameserver-policy:
    'rule-set:youtube_api':  https://1.1.1.1/dns-query#specified

  enhanced-mode: fake-ip
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP

proxies: []
proxy-groups: []

rule-providers:
  youtube_api:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/john-smith-matter/vpn_conf/refs/heads/main/youtube_api.yaml
    path: ./rulesets/youtube_api.yaml
  youtube_cdn:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/john-smith-matter/vpn_conf/refs/heads/main/youtube_cdn.yaml
    path: ./rulesets/youtube_cdn.yaml
  microsoft:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.yaml
    path: ./rulesets/microsoft.yaml
  forbidden:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/john-smith-matter/vpn_conf/refs/heads/main/forbidden.yaml
    path: ./rulesets/forbidden.yaml

rules:
  ## cloudflare-dns
  - DOMAIN,cloudflare-dns.com,default
  - IP-CIDR,1.1.1.1/32,default
  - IP-CIDR,1.0.0.1/32,default
  ## github
  - DOMAIN-KEYWORD,github,default
    
  ## youtube
  - RULE-SET,youtube_cdn,default
  - RULE-SET,youtube_api,specified

  ## microsoft
  - RULE-SET,microsoft,default

  ## IP测试
  - DOMAIN-SUFFIX,ifconfig.me,specified

  ## 禁止访问
  - RULE-SET,forbidden,default
  
  ## 直连
  - DOMAIN-SUFFIX,nubia.com,DIRECT
  - DOMAIN-SUFFIX,nubia.cn,DIRECT
  - DOMAIN-SUFFIX,zte.com.cn,DIRECT
  - DOMAIN-SUFFIX,redmagic.com,DIRECT
  - DOMAIN-SUFFIX,feishu.cn,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT
  - GEOSITE,cn,DIRECT
  - GEOIP,cn,DIRECT
  - GEOIP,private,DIRECT,no-resolve
  
  ## 广告阻止
  - GEOSITE,category-public-tracker,REJECT
  
  - MATCH,default
