mixed-port: 7890
mode: rule
external-controller: 127.0.0.1:9090

# geoip设置
geodata-mode: false
geox-url:
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/latest/download/country-lite.mmdb"
etag-support: true
global-ua: clash.meta

dns:
  enable: true
  listen: 127.0.0.1:53
  ipv6: false
  dns-direct-nameserver:
    - 1.1.1.1
    - 1.0.0.1
  proxy-server-nameserver:
    - 1.1.1.1
    - 1.0.0.1
  nameserver:
    - https://1.1.1.1/dns-query#default
    - https://1.0.0.1/dns-query#default

  nameserver-policy:
    'rule-set:Youtube':  https://1.1.1.1/dns-query#specified
    'rule-set:YoutubeMusic': https://1.1.1.1/dns-query#specified
    'rule-set:Google': https://1.1.1.1/dns-query#specified

  enhanced-mode: fake-ip
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP

proxies: []
proxy-groups: []

rules:
  ## cloudflare-dns
  - DOMAIN,cloudflare-dns.com,default
  - IP-CIDR,1.1.1.1/32,default
  - IP-CIDR,1.0.0.1/32,default
  ## github
  - DOMAIN-KEYWORD,github,default
    
  ## youtube content delivery
  - DOMAIN-SUFFIX,googlevideo.com,default
  - DOMAIN-SUFFIX,ytimg.com,default
  - DOMAIN-SUFFIX,video.google.com,default
  ## google & youtube api
  - DOMAIN-KEYWORD,youtube,specified
  - DOMAIN-SUFFIX,youtu.be,specified
  - DOMAIN-SUFFIX,yt.be,specified
  - DOMAIN-SUFFIX,ggpht.cn
  - DOMAIN-SUFFIX,ggpht.com
  - DOMAIN-SUFFIX,gvt1.com
  - DOMAIN-SUFFIX,gvt2.com
  - DOMAIN-KEYWORD,google,specified
  - DOMAIN-KEYWORD,gstatic,specified
  - DOMAIN-SUFFIX,abc.xyz,specified

  ## IP测试
  - DOMAIN-SUFFIX,ifconfig.me,specified
  
  ## 直连
  - DOMAIN-SUFFIX,nubia.com,DIRECT
  - DOMAIN-SUFFIX,nubia.cn,DIRECT
  - DOMAIN-SUFFIX,zte.com.cn,DIRECT
  - DOMAIN-SUFFIX,redmagic.com,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT
  - GEOSITE,cn,DIRECT
  - GEOIP,cn,DIRECT
  - GEOIP,private,DIRECT,no-resolve
  
  ## 广告阻止
  - GEOSITE,category-public-tracker,REJECT
  
  - MATCH,default
